
package com.css.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SayHiService", targetNamespace = "http://service.css.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SayHiService {


    /**
     * 
     */
    @WebMethod
    public void sayHiDefault();

    /**
     * 
     * @param clientTime
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "valid", partName = "valid")
    public int checkTime(
            @WebParam(name = "clientTime", partName = "clientTime")
                    XMLGregorianCalendar clientTime);

    /**
     * 
     * @param name
     */
    @WebMethod
    public void sayHi(
            @WebParam(name = "name", partName = "name")
                    String name);

}
